blog/urls.py
from django.conf.urls import patterns, url
from blog import views


urlpatterns = patterns(
    '',
    url(r'^$', views.PostListView.as_view(), name='post_list'),
    url(r'^admin/$', views.PostAdminListView.as_view(), name='blog_admin'),
    url(r'^admin/create/$', views.BlogPostCreateView.as_view(), name='create_post'),
    url(r'^admin/edit/(?P<pk>\d+)/$', views.BlogPostEditView.as_view(), name='edit_post'),
    url(r'^admin/delete/(?P<pk>\d+)/$', views.DeleteBlogPost.as_view(), name='delete_post'),
    url(r'^admin/image_upload/$', views.PostImageUploader.as_view(), name="upload_blog_image"),
    url(r'^admin/image_link/(?P<pk>\d+)/$', views.PostImageLink.as_view(), name="blog_image_link"),
    url(r'^author/(?P<pk>\d+)/$', views.AuthorPostListView.as_view(), name="author_post_list"),
    url(r'^tag/(?P<tag>[\w-]+)/$', views.TagPostListView.as_view(), name="tag_post_list"),
    url(r'^(?P<slug>[\w-]+)/$', views.PostDetailView.as_view(), name='blog_post'),
    url(r'^(?P<slug>[\w-]+)/preview/$', views.PostPreviewView.as_view(), name='blog_post_preview'),
)

blohaute/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic.base import TemplateView
from booking.views import (TreatmentList, TreatmentDetail, contact_view, schedule, PackagePaymentView,
                           PaymentView, available_times_for_day, add_treatment_to_cart,
                           AppointmentList, TimeSlotList, CreateAppointment, CancelAppointment, AvailableStylistList,
                           product_list, BridalServices)
from accounts.views import UserProfile, ObtainAuthToken, ForgotPassword, RegisterUser
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('',

    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('accounts.urls')),
    url(r'^$', TemplateView.as_view(template_name="index.html"), name='home'),
    url(r'^about/', TemplateView.as_view(template_name="about.html"), name='about'),
    url(r'^contact/', contact_view, name='contact'),
    url(r'^stylists/', TemplateView.as_view(template_name="stylists.html"), name='stylists'),
    url(r'^products/', product_list, name='products'),
    url(r'^blog/', include('blog.urls')),

    url(r'^cart/', include('changuito.urls')),
    url(r'^schedule/', schedule, name='schedule'),
    url(r'^payment/', PaymentView.as_view(), name='payment'),

    url(r'^styles/', TemplateView.as_view(template_name="styles.html"), name='styles'),
    url(r'^book/', TreatmentList.as_view(template_name="services.html"), name='book'),
    url(r'^timesforday/', available_times_for_day, name='timesforday'),

    url(r'^bridal_services/$', BridalServices.as_view(), name='bridal_services'),

    url(r'^(?P<slug>\w+)/$', TreatmentDetail.as_view(), name='treatment_detail'),
    url(r'^(?P<slug>\w+)/add/$', add_treatment_to_cart, name='treatment_book'),
    url(r'^(?P<slug>\w+)/package/(?P<pk>\d+)/checkout/$', PackagePaymentView.as_view(), name='package_checkout'),

    url(r'^api/auth/login/$', ObtainAuthToken.as_view()),
    url(r'^api/auth/forgot_password/$', ForgotPassword.as_view()),
    url(r'^api/auth/register/$', RegisterUser.as_view()),
    url(r'^api/profile/$', UserProfile.as_view()),
    url(r'^api/appointments/$', AppointmentList.as_view()),
    url(r'^api/appointments/book/$', CreateAppointment.as_view()),
    url(r'^api/appointments/(?P<booker_id>\d+)/cancel/$', CancelAppointment.as_view()),
    url(r'^api/availability/(?P<booker_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/$', TimeSlotList.as_view()),
    url(r'^api/availability/stylists/$', AvailableStylistList.as_view(), name="available_stylists")

    ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

booking/models.py
from django.db import models
from django.contrib.humanize.templatetags.humanize import apnumber
from django.template.defaultfilters import floatformat
from adminsortable.models import Sortable
from booking.booker_client.dates import *


class Treatment(Sortable):
    name = models.CharField(max_length=255)
    plural_name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=50, unique=True)
    booker_id = models.IntegerField(null=True, blank=True)
    list_tagline = models.CharField(max_length=255, blank=True)
    list_image = models.ImageField(upload_to='treatment_images')
    thumb_image = models.ImageField(upload_to='thumbnail_images')
    description = models.TextField(blank=True)
    price = models.DecimalField(default=0.00, max_digits=10, decimal_places=2)
    original_price = models.DecimalField(default=0.00, max_digits=10, decimal_places=2, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta(Sortable.Meta):
        pass

    def __unicode__(self):
        return self.name

    def cart_description(self):
        return self.name

    @property
    def list_image_url(self):
        print self.list_image
        if self.list_image and hasattr(self.list_image, 'url'):
            return self.list_image.url

    @property
    def thumb_image_url(self):
        print self.thumb_image
        if self.thumb_image and hasattr(self.list_image, 'url'):
            return self.thumb_image.url

    def price_units(self):
        return ""


class TreatmentImage(models.Model):
    treatment = models.ForeignKey(Treatment, related_name="images")
    image = models.ImageField(blank=True, null=True, upload_to='treatment_images')
    primary_image = models.BooleanField(default=False)


class Package(models.Model):
    booker_id = models.IntegerField(null=True, blank=True)
    treatment = models.ForeignKey(Treatment, related_name="packages")
    quantity = models.IntegerField()
    price = models.DecimalField(default=0.00, max_digits=10, decimal_places=2)

    def __unicode__(self):
        return "%s Pack - $%s" % ((str(apnumber(self.quantity)).capitalize()), floatformat(self.price, -2))

    def cart_description(self):
        return "%s - %s Pack" % (self.treatment.name, self.quantity)

    def price_units(self):
        return ""

    def slug(self):
        return self.treatment.slug

    def thumb_image_url(self):
        return self.treatment.thumb_image_url


class Membership(models.Model):
    booker_id = models.IntegerField(null=True, blank=True)
    treatment = models.ForeignKey(Treatment, related_name="memberships")
    quantity = models.IntegerField()
    price = models.DecimalField(default=0.00, max_digits=10, decimal_places=2)

    def __unicode__(self):
        return "%d %s / $%s per month" % (self.quantity, self.treatment.plural_name, floatformat(self.price, -2))

    def cart_description(self):
        return "%s Membership - %s per month" % (self.treatment.name, self.quantity)

    def price_units(self):
        return "/ month"

    def slug(self):
        return self.treatment.slug

    def thumb_image_url(self):
        return self.treatment.thumb_image_url


class CustomerSeries(object):
    series_id = None
    name = None
    quantity = None
    remaining = None
    expiration = None
    redeemable_items = None
    treatment = None

    def __init__(self, series_id, name, quantity, remaining, expiration, redeemable):
        self.series_id = series_id
        self.name = name
        self.quantity = quantity
        self.remaining = remaining
        # self.expiration = expiration
        self.redeemable_items = redeemable
        treatment_id = self.redeemable_items[0]['TreatmentID']
        self.treatment = Treatment.objects.get(booker_id=treatment_id)

    def __str__(self):
        if self.expiration is None:
            self.expiration = "Never"
        return self.name + " " + str(self.remaining) + " of " + str(self.quantity)


class IdCache:
    TREATMENT_IDS = {'Updo': 1500556, 'Braid': 1500553, 'Blow Out': 1500539}
    employees = {'Amanda I': 322953,
                 'Amanda S/D': 319599,
                 'Jessie Hitzeman': 319544,
                 'Morgan': 319549,
                 'Jesse Scheele': 322667,
                 'April Telman': 322866}


class AvailableTimeSlot(object):
    single_employee_slots = []
    multiple_employee_slots = []
    pretty_time = ''

    def __eq__(self, other):
        return self.pretty_time == other.pretty_time

    def __hash__(self):
        return hash(self.pretty_time)

    def __str__(self):
        return "%s has %d single and %d multiple employee slots" % (self.pretty_time,
                                                                    len(self.single_employee_slots),
                                                                    len(self.multiple_employee_slots))


class BookerModel(object):
    pass


class AppointmentItem(BookerModel):
    appointment_id = None
    datetime = None
    treatment = None
    employee_name = None

    def __init__(self, data=None):
        if data:
            self.appointment_id = data['AppointmentID']
            self.datetime = parse_date(data['StartDateTime'])
            self.treatment_id = data['Treatment']['ID']
            self.treatment_name = data['Treatment']['Name']
            self.employee_name = data['Employee']['FirstName']
            try:
                self.treatment = Treatment.objects.get(booker_id=self.treatment_id)
            except Treatment.DoesNotExist:
                self.treatment = Treatment(booker_id=self.treatment_id)
            print 'created appointment id %d' % self.appointment_id

    def __unicode__(self):
        return "%s at %s on %s" % (self.treatment.name, self.datetime.strftime('H:i'), self.datetime.strftime('yyyy-mm-dd'))


class Appointment(BookerModel):
    id = None
    status = None
    customer_id = None
    booking_number = None
    start_datetime = None
    end_datetime = None
    final_total = None
    can_cancel = None
    treatments = []
    payment = None
    address = None
    raw = None

    def __init__(self, data=None):
        if data:
            self.id = data['ID']
            self.booking_number = data['BookingNumber']
            self.customer_id = data['CustomerID']
            self.start_datetime = parse_date(data['StartDateTime'])
            self.end_datetime = parse_date(data['EndDateTime'])
            self.final_total = data['FinalTotal']['Amount']
            self.status = data['Status']['ID']
            self.can_cancel = data['CanCancel']
            self.treatments = []
            self.payment = data['AppointmentPayment']
            self.address = data['Customer']['Address']
            for appointment in data['AppointmentTreatments']:
                treatment = AppointmentItem(appointment)
                self.treatments.append(treatment)
            self.raw = data

    def is_past(self):
        return datetime.now() - self.start_datetime > timedelta(minutes=5)

    def duration(self):
        return self.end_datetime - self.start_datetime


class AppointmentManager(object):
    """
    work in progress. Should be able to do basic querying operations for appointments
    """

    user = None
    client = None

    def __init__(self, user):
        self.user = user

    def all(self, client):
        return self.client.get_appointments()

    def get(self, id):
        return self.client.get_appointment(id)

    def cancel(self, id):
        return self.client.cancel_appointment(id)


class GenericItem(object):
    product = None
    quantity = 1
    source = None

    def __init__(self, product, quantity=1, price=None):
        self.product = product
        self.quantity = quantity
        self.price = price

    def total_price(self):
        return float(self.quantity) * float(self.product.price)
    total_price = property(total_price)

    def total_price_display(self):
        return "$%s %s" % (floatformat(self.total_price, -2), self.product.price_units())


class Order(object):
    items = []
    discount_text = None
    discount_amount = None
    coupon_code = None
    itenerary = None
    appointment = None

    def total_price(self):
        total = sum(i.total_price for i in self.items)
        if self.discount_amount:
            total -= self.discount_amount
        return total

    def total_price_display(self):
        return "$%s" % (floatformat(self.total_price(), -2))

booking/forms.py
from django import forms
from django.forms.formsets import formset_factory
from localflavor.us.forms import USZipCodeField, USStateField
from booking.models import Package, Membership, Treatment
from booking.fields import CreditCardField, ExpiryDateField, VerificationValueField
from booking.zip_codes import ZIP_CODE_LIST

class QuickBookForm(forms.Form):
    treatment = forms.ModelChoiceField(queryset=Treatment.objects.all(),
                                       widget=forms.HiddenInput())


class AddToCartForm(forms.Form):
    package = forms.ChoiceField(required=False)
    membership = forms.ModelChoiceField(queryset=Membership.objects.all(),
                                        required=False,
                                        empty_label="Select a Membership")

    def __init__(self, *args, **kwargs):
        self.treatment = kwargs.pop('treatment', None)
        super(AddToCartForm, self).__init__(*args, **kwargs)

        if self.treatment:
            packages = Package.objects.filter(treatment=self.treatment)
            choices = [('', 'Select a Package'), ]

            choices.extend([(package.id, package.__unicode__()) for package in packages])
            self.fields['package'].choices = choices
            self.fields['membership'].queryset = Membership.objects.filter(treatment=self.treatment)

    def clean(self):
        if (self.cleaned_data['package'] is None and self.cleaned_data['membership'] is None):
            print 'raising validation error'
            raise forms.ValidationError('You must select either a package or a \
                                        membership to add to the cart')

    def clean_package(self):
        package = self.cleaned_data['package']
        if package == '':
            return None
        return Package.objects.filter(treatment=self.treatment).get(pk=package)


class CouponForm(forms.Form):
    coupon_code = forms.CharField()


class PaymentForm(forms.Form):
    name_on_card = forms.CharField(error_messages={'required': 'Enter the name on your credit card'})
    card_number = CreditCardField(error_messages={'required': 'Enter your credit card number'})
    expiry_date = ExpiryDateField()
    card_code = VerificationValueField(label="CVV")
    billing_zip_code = USZipCodeField(label="Billing Zip", error_messages={'required': 'ZIP is required'})


class SelectAvailableServiceForm(forms.Form):
    series = None
    treatment = None
    treatment_id = forms.IntegerField(widget=forms.HiddenInput())
    quantity = forms.ChoiceField()

    def __init__(self, *args, **kwargs):
        super(SelectAvailableServiceForm, self).__init__(*args, **kwargs)
        self.series = kwargs['initial'].get('series', None)
        self.treatment = self.series.treatment
        self.fields['quantity'].choices = [(x, x) for x in range(0, self.series.remaining + 1)]

#use the factory to create the base model for us
BaseAvailableServiceFormset = formset_factory(SelectAvailableServiceForm, extra=0)


class AvailableServiceFormset(BaseAvailableServiceFormset):
    series = None

    def __init__(self, *args, **kwargs):
        self.series = kwargs.pop('series')
        kwargs['initial'] = [{'treatment_id': s.treatment.pk, 'quantity': 0, 'series': s} for s in self.series]
        super(AvailableServiceFormset, self).__init__(*args, **kwargs)

    def _construct_form(self, *args, **kwargs):
        # inject user in each form on the formset
        #kwargs['user'] = self.user
        return super(AvailableServiceFormset, self)._construct_form(*args, **kwargs)


class ScheduleServiceForm(forms.Form):
    address = forms.CharField()
    city = forms.CharField(widget=forms.Select(choices=(('Chicago', 'Chicago',), )))
    state = USStateField(widget=forms.Select(choices=(('IL', 'IL',), )))
    zip_code = USZipCodeField()

    CHOICES = (('0', 'Loading Stylists',), )
    stylist = forms.CharField(widget=forms.Select(choices=CHOICES))
    date = forms.DateField()
    time = forms.CharField()

    def clean_zip_code(self):
        data = self.cleaned_data['zip_code']

        if int(data) not in ZIP_CODE_LIST:
            raise forms.ValidationError("Sorry! Service is currently limited to Chicago")
        return data


class ContactForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea())


class RescheduleForm(forms.Form):
    date = forms.DateField()
    time = forms.CharField()


class BridalServicesForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    date_of_wedding = forms.DateField()
    number_of_bridesmaids = forms.CharField()
    location = forms.CharField()

booking/templates/booking/payment.html
{% extends "minimal_base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block page_title %}Checkout{% endblock %}

{% block content %}

<div class="bh-position">
    <div class="uk-container uk-container-center">

        <ul class="uk-breadcrumb">
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'book' %}">Book</a></li>
            <li class="uk-active"><span>Checkout</span></li>
        </ul>

        <article class="uk-article">
            <div class="uk-grid" data-uk-grid-margin>
                {% if payment_form.errors %}
                <div class="uk-width-1-1">
                    <div class="uk-alert uk-alert-danger ">
                        {% if payment_form.non_field_errors %}
                            {% for error in payment_form.non_field_errors %}
                                <p>{{error}}</p>
                            {% endfor %}
                        {% else %}
                            There was a problem booking your order. Please correct the errors below and try again.
                        {% endif %}

                    </div>
                </div>
                {% endif %}
                <div class="uk-width-1-1">
                    {% with WIDGET_ERROR_CLASS='uk-form-danger' WIDGET_REQUIRED_CLASS='required' %}
                        {% for hidden in payment_form.hidden_fields %}
                            {{ hidden }}
                        {% endfor %}
               
                        <div class="uk-grid uk-margin-large-top" data-uk-grid-margin>
                    
                            <form id="payment-form" method="POST" class="uk-form uk-width-medium-1-2">
                                {% csrf_token %}
                                {% include 'form_snippets/appointment_payment.html' %}
                            </form>   
    
                            <div class="uk-width-medium-1-2" id="order-summary-container">
                                {% include 'form_snippets/order_summary.html' %}
                            </div>
                        </div>
                        <div class="uk-grid uk-margin-large-top" data-uk-grid-margin>
                            <div class="uk-width-medium-1-1 uk-container-center">
                                <button class="uk-button uk-button-primary" id="place-order-button">Place Order</button>
                            </div>
                        </div>
                    {% endwith %}
                </div>
            </div>
        </article>

    </div>
</div>
{% endblock %}

{% block extrajs %}
<script>
$(document).ready(function() {
    $("#place-order-button").click(function() {
        $("#payment-form").submit();
    });
});

</script>
{% endblock %}

booking/templates/booking/schedule.html
{% extends "minimal_base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block page_title %}Checkout{% endblock %}

{% block content %}

<div class="bh-position">
    <div class="uk-container uk-container-center">

        <ul class="uk-breadcrumb">
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'book' %}">Book</a></li>
            <li class="uk-active"><span>Checkout</span></li>
        </ul>

        <article class="uk-article">
            <div class="uk-grid" data-uk-grid-margin>
                    {% if schedule_form.errors %}
                    <div class="uk-width-1-1">
                        <div class="uk-alert uk-alert-danger ">
                            {% if schedule_form.non_field_errors %}
                                {% for error in schedule_form.non_field_errors %}
                                    <p>{{error}}</p>
                                {% endfor %}
                            {% else %}
                                There was a problem booking your order. Please correct the errors below and try again.
                            {% endif %}

                        </div>
                    </div>
                    {% endif %}
                    <div class="uk-width-1-1">
                        {% with WIDGET_ERROR_CLASS='uk-form-danger' WIDGET_REQUIRED_CLASS='required' %}
                        <form method="POST" class="uk-form">
                            {% csrf_token %}
                            {% for hidden in schedule_form.hidden_fields %}
                                {{ hidden }}
                            {% endfor %}

                            <div class="uk-grid uk-margin-large-top" data-uk-grid-margin>
                                <div class="uk-width-medium-1-2">
                                    {% include 'form_snippets/appointment_location.html' %}
                                </div>
                                <div class="uk-width-medium-1-2">
                                    {% include 'form_snippets/appointment_schedule.html' %}
                                </div>
                            </div>
                            <div class="uk-grid uk-margin-large-top" data-uk-grid-margin>

                                <div class="uk-width-medium-1-1 uk-container-center">
                                    <button class="uk-button uk-button-primary">Continute Checkout</button>

                                </div>
                            </div>
                        </form>
                        {% endwith %}
                    </div>
            </div>
        </article>

    </div>
</div>
{% endblock %}

{% block extracss %}
<link rel="stylesheet" href="{% static 'js/pickadate/themes/classic.css' %}">
<link rel="stylesheet" href="{% static 'js/pickadate/themes/classic.date.css' %}">
<link rel="stylesheet" href="{% static 'js/pickadate/themes/classic.time.css' %}">
{% endblock %}

{% block extrajs %}
<script src="{% static 'js/pickadate/picker.js' %}"></script>
<script src="{% static 'js/pickadate/picker.date.js' %}"></script>
<script src="{% static 'js/pickadate/picker.time.js' %}"></script>
<script src="{% static 'js/pickadate/legacy.js' %}"></script>


<script>
$(document).ready(function() {

    var datesLoaded = false;

    var $idCheckoutTime = $('#id_time');
    $idCheckoutTime.hide();
    var timeInput = $idCheckoutTime.pickatime({
        formatSubmit: 'HH:i',
        hiddenName: true,
        min: [7, 0],
        max: [20, 0],
        interval: 15
    });

    var timePicker = timeInput.pickatime('picker');
    timePicker.set('disable', true); //start with all times disabled

    var $idCheckout = $("#id_date");
    $idCheckout.hide();
    var datePicker = $idCheckout.pickadate({
        disable: null,
        format: 'ddd mmmm d yyyy',
        formatSubmit: 'yyyy-mm-dd',
        hiddenName: true,
        close: '',
        today: '',
        clear: '',
        min: new  Date(),

        beforeSend: function() {
                console.log("beforeSend fired");
                $( "#spinner" ).append( "<div id='loading-container'><img src='{% static 'images/loading.gif' %}' id='spinning-loader' alt='loading' /></div>" );
        },
        complete: function() {
                console.log("complete fired");
                $( "#loading-container" ).remove();
                $( "#spinning-loader" ).remove();
        },
        onSet: function(context) {
            var $idCheckoutHidden = $("#id_date_hidden");
            
            if (context['select'] && $idCheckoutHidden.val()) {
                $('#appointment-loading').fadeIn();

                timePicker.set('disable', true);
                $.ajax({
                    type: 'POST',
                    url: '{% url "timesforday" %}',
                    dataType: 'json',
                    data: {
                        date: $idCheckoutHidden.val(),
                        stylist: $('#id_stylist').val()
                    },
                    success: function(data) {
                        timePicker.set('disable', data);
                        $('#appointment-loading').fadeOut();
                    }
                });
            }
        }
    });
    var picker = datePicker.pickadate('picker');

    if ($idCheckout.val() != "") {
        picker.set('select', $idCheckout.val(), { format: 'yyyy-mm-dd' })
    }
    picker.open(false);


    if ($idCheckoutTime.val() != "") {
        timePicker.set('select', $idCheckoutTime.val(), { format: 'HH:i' })
    }


    $('#appointment-schedule').css({position: 'relative'});
    var spinner = new Spinner().spin();
    $(spinner.el).appendTo(document.getElementById('appointment-loading'));

    $('#appointment-loading').hide();


    //make time and date borders red if there are errors
    if ($idCheckout.hasClass('uk-form-danger')) {
        $("#id_checkout-date_root").find('.picker__holder').addClass('uk-form-danger');
    }
    if ($idCheckoutTime.hasClass('uk-form-danger')) {
        $("#id_checkout-time_root").find('.picker__holder').addClass('uk-form-danger');
    }
    //Select stylists
    var stylistSelect = $('#id_stylist');
    stylistSelect.prop('disabled', true);
    $.ajax({
        type: 'GET',
        url: "{% url 'available_stylists' %}",
        dataType: 'json',
        success: function(data) {
        $.each(data, function(key, value) {
            stylistSelect
         .append($("<option></option>")
         .attr("value",value["ID"])
         .text(value["name"]));

        });
            $('#id_stylist option:first').text('Any Stylist');
            stylistSelect.prop('disabled', false);
        }
    });
    stylistSelect.change(function() {
        //Trigger the date selection if we have a date selected already
        if (picker.get('select')) {
            picker.set('select', picker.get('select'));
        }
    });
});

</script>
{% endblock %}

booking/templates/booking/service_menu.html
{% for treatment in treatments %}
<li>
	<a href="{% url 'treatment_detail' treatment.slug %}">{{treatment.plural_name}}</a>
</li>
{% endfor %}
<li>
    <a href="{% url 'bridal_services'%}">Bridal Services</a>
</li>

booking/templates/booking/treatment_slider.html
{% load staticfiles %}

<div class="uk-width-1-1">
    <div class="uk-panel uk-panel-header">
        <div class="uk-panel-title">There’s more looks where that came from.</div>
        <div class="slick-slider" data-uk-check-display>
            {% for treatment in treatments %}
            <div>
                <div class="uk-panel">
                    <div class="bh-product-overlay">
                        <a href="{% url 'treatment_detail' treatment.slug %}"></a>
                        <img class="bh-product-overlay-img" src="{{treatment.list_image_url}}" width="720" height="540" alt="Blohaute braids">
                        <img class="bh-product-overlay-img-hover" src="{{treatment.list_image_url}}" width="720" height="540" alt="Blohaute braids">
                        <div class="bh-product-overlay-content">
                            <div class="uk-button-group uk-width-1-1">
                                <a href="{% url 'treatment_detail' treatment.slug %}" class="uk-button uk-button-large uk-width-8-10">View {{treatment.name}} Services</a>
                                <a href="{% url 'treatment_detail' treatment.slug %}" class="uk-button uk-button-large uk-width-2-10"><i class="uk-icon-star"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="uk-float-left uk-margin-top">
                        <h3 class="uk-margin-small-bottom uk-link-reset"><a href="#">{{treatment.name}}</a></h3>                              
                    </div>
                    <span class="uk-float-right uk-margin-top uk-text-large">${{treatment.price|floatformat:"-2"}}</span>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<br /><br /><br />