blog/urls.py
from django.conf.urls import patterns, url
from blog import views


urlpatterns = patterns(
    '',
    url(r'^$', views.PostListView.as_view(), name='post_list'),
    url(r'^admin/$', views.PostAdminListView.as_view(), name='blog_admin'),
    url(r'^admin/create/$', views.BlogPostCreateView.as_view(), name='create_post'),
    url(r'^admin/edit/(?P<pk>\d+)/$', views.BlogPostEditView.as_view(), name='edit_post'),
    url(r'^admin/delete/(?P<pk>\d+)/$', views.DeleteBlogPost.as_view(), name='delete_post'),
    url(r'^admin/image_upload/$', views.PostImageUploader.as_view(), name="upload_blog_image"),
    url(r'^admin/image_link/(?P<pk>\d+)/$', views.PostImageLink.as_view(), name="blog_image_link"),
    url(r'^author/(?P<pk>\d+)/$', views.AuthorPostListView.as_view(), name="author_post_list"),
    url(r'^tag/(?P<tag>[\w-]+)/$', views.TagPostListView.as_view(), name="tag_post_list"),
    url(r'^(?P<slug>[\w-]+)/$', views.PostDetailView.as_view(), name='blog_post'),
    url(r'^(?P<slug>[\w-]+)/preview/$', views.PostPreviewView.as_view(), name='blog_post_preview'),
)

blohaute/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic.base import TemplateView
from booking.views import (TreatmentList, TreatmentDetail, contact_view, schedule, PackagePaymentView,
                           PaymentView, available_times_for_day, add_treatment_to_cart,
                           AppointmentList, TimeSlotList, CreateAppointment, CancelAppointment, AvailableStylistList,
                           product_list, BridalServices)
from accounts.views import UserProfile, ObtainAuthToken, ForgotPassword, RegisterUser
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('',

    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('accounts.urls')),
    url(r'^$', TemplateView.as_view(template_name="index.html"), name='home'),
    url(r'^about/', TemplateView.as_view(template_name="about.html"), name='about'),
    url(r'^contact/', contact_view, name='contact'),
    url(r'^stylists/', TemplateView.as_view(template_name="stylists.html"), name='stylists'),
    url(r'^products/', product_list, name='products'),
    url(r'^blog/', include('blog.urls')),

    url(r'^cart/', include('changuito.urls')),
    url(r'^schedule/', schedule, name='schedule'),
    url(r'^payment/', PaymentView.as_view(), name='payment'),

    url(r'^styles/', TemplateView.as_view(template_name="styles.html"), name='styles'),
    url(r'^book/', TreatmentList.as_view(template_name="services.html"), name='book'),
    url(r'^timesforday/', available_times_for_day, name='timesforday'),

    url(r'^bridal_services/$', BridalServices.as_view(), name='bridal_services'),

    url(r'^(?P<slug>\w+)/$', TreatmentDetail.as_view(), name='treatment_detail'),
    url(r'^(?P<slug>\w+)/add/$', add_treatment_to_cart, name='treatment_book'),
    url(r'^(?P<slug>\w+)/package/(?P<pk>\d+)/checkout/$', PackagePaymentView.as_view(), name='package_checkout'),

    url(r'^api/auth/login/$', ObtainAuthToken.as_view()),
    url(r'^api/auth/forgot_password/$', ForgotPassword.as_view()),
    url(r'^api/auth/register/$', RegisterUser.as_view()),
    url(r'^api/profile/$', UserProfile.as_view()),
    url(r'^api/appointments/$', AppointmentList.as_view()),
    url(r'^api/appointments/book/$', CreateAppointment.as_view()),
    url(r'^api/appointments/(?P<booker_id>\d+)/cancel/$', CancelAppointment.as_view()),
    url(r'^api/availability/(?P<booker_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/$', TimeSlotList.as_view()),
    url(r'^api/availability/stylists/$', AvailableStylistList.as_view(), name="available_stylists")

    ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

booking/forms.py
from django import forms
from django.forms.formsets import formset_factory
from localflavor.us.forms import USZipCodeField, USStateField
from booking.models import Package, Membership, Treatment
from booking.fields import CreditCardField, ExpiryDateField, VerificationValueField
from booking.zip_codes import ZIP_CODE_LIST

class QuickBookForm(forms.Form):
    treatment = forms.ModelChoiceField(queryset=Treatment.objects.all(),
                                       widget=forms.HiddenInput())


class AddToCartForm(forms.Form):
    package = forms.ChoiceField(required=False)
    membership = forms.ModelChoiceField(queryset=Membership.objects.all(),
                                        required=False,
                                        empty_label="Select a Membership")

    def __init__(self, *args, **kwargs):
        self.treatment = kwargs.pop('treatment', None)
        super(AddToCartForm, self).__init__(*args, **kwargs)

        if self.treatment:
            packages = Package.objects.filter(treatment=self.treatment)
            choices = [('', 'Select a Package'), ]

            choices.extend([(package.id, package.__unicode__()) for package in packages])
            self.fields['package'].choices = choices
            self.fields['membership'].queryset = Membership.objects.filter(treatment=self.treatment)

    def clean(self):
        if (self.cleaned_data['package'] is None and self.cleaned_data['membership'] is None):
            print 'raising validation error'
            raise forms.ValidationError('You must select either a package or a \
                                        membership to add to the cart')

    def clean_package(self):
        package = self.cleaned_data['package']
        if package == '':
            return None
        return Package.objects.filter(treatment=self.treatment).get(pk=package)


class CouponForm(forms.Form):
    coupon_code = forms.CharField()


class PaymentForm(forms.Form):
    name_on_card = forms.CharField(error_messages={'required': 'Enter the name on your credit card'})
    card_number = CreditCardField(error_messages={'required': 'Enter your credit card number'})
    expiry_date = ExpiryDateField()
    card_code = VerificationValueField(label="CVV")
    billing_zip_code = USZipCodeField(label="Billing Zip", error_messages={'required': 'ZIP is required'})


class SelectAvailableServiceForm(forms.Form):
    series = None
    treatment = None
    treatment_id = forms.IntegerField(widget=forms.HiddenInput())
    quantity = forms.ChoiceField()

    def __init__(self, *args, **kwargs):
        super(SelectAvailableServiceForm, self).__init__(*args, **kwargs)
        self.series = kwargs['initial'].get('series', None)
        self.treatment = self.series.treatment
        self.fields['quantity'].choices = [(x, x) for x in range(0, self.series.remaining + 1)]

#use the factory to create the base model for us
BaseAvailableServiceFormset = formset_factory(SelectAvailableServiceForm, extra=0)


class AvailableServiceFormset(BaseAvailableServiceFormset):
    series = None

    def __init__(self, *args, **kwargs):
        self.series = kwargs.pop('series')
        kwargs['initial'] = [{'treatment_id': s.treatment.pk, 'quantity': 0, 'series': s} for s in self.series]
        super(AvailableServiceFormset, self).__init__(*args, **kwargs)

    def _construct_form(self, *args, **kwargs):
        # inject user in each form on the formset
        #kwargs['user'] = self.user
        return super(AvailableServiceFormset, self)._construct_form(*args, **kwargs)


class ScheduleServiceForm(forms.Form):
    address = forms.CharField()
    city = forms.CharField(widget=forms.Select(choices=(('Chicago', 'Chicago',), )))
    state = USStateField(widget=forms.Select(choices=(('IL', 'IL',), )))
    zip_code = USZipCodeField()

    CHOICES = (('0', 'Loading Stylists',), )
    stylist = forms.CharField(widget=forms.Select(choices=CHOICES))
    date = forms.DateField()
    time = forms.CharField()

    def clean_zip_code(self):
        data = self.cleaned_data['zip_code']

        if int(data) not in ZIP_CODE_LIST:
            raise forms.ValidationError("Sorry! Service is currently limited to Chicago")
        return data


class ContactForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea())


class RescheduleForm(forms.Form):
    date = forms.DateField()
    time = forms.CharField()


class BridalServicesForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    date_of_wedding = forms.DateField()
    number_of_bridesmaids = forms.CharField()
    location = forms.CharField()

templates/about.html
{% extends "base.html" %}
{% load staticfiles %}

{% block page_title %}About{% endblock %}

{% block content %}
<div class="bh-position bh-position-light bh-position-title">
	<div class="uk-container uk-container-center">
	    <div class="uk-panel">
	        <h1>About BloHaute</h1>
	    </div>
    </div>
</div>

<div class="bh-position">
	<div class="uk-container uk-container-center">
		<article class="uk-article">
			<p class="bh-article-columns uk-text-justify"><span class="bh-dropcap">B</span>lohaute is Chicago’s premier beauty brand, employing the industry’s top professionals to give you that elegant look you’ve been waiting for. It’s our passion to make you feel good and to deliver the latest lust-have looks. As Chicago’s first on-demand beauty service, Blohaute promises convenience like you’ve never experienced. Simply sign-up for an appointment online, and you’ll be treated to a salon-like experience without ever having to leave your home. So what are you waiting for? Book an appointment today and treat yourself to a Blohaute.</p>

			<div class="uk-grid uk-margin-top" data-uk-grid-margin data-uk-grid-match="{target:'> div > .uk-panel'}">

			  	<div class="uk-width-medium-1-3">
			    	<div class="uk-panel uk-panel-box uk-text-center">
			    		<i class="bh-icon-large uk-icon-home"></i>
			      		<h3>In-home styling’s</h3>
			      		<p>Name the time and the place, even as late as an hour before! We are ready and prepared to take the best care of you in the comfort of your own home or venue of your choice.</p>
                        <a class="uk-button bh-button-secondary" href="{% url 'book' %}">See Our Services</a>
			    	</div>
			  	</div>

			  	<div class="uk-width-medium-1-3">
			    	<div class="uk-panel uk-panel-box uk-text-center">
			    		<i class="bh-icon-large uk-icon-scissors"></i>
			      		<h3>Industry-leading hair stylists</h3>
			      		<p>We only hire the best talent and it shows. We have had incredible feedback from our customers and our proud of our work.</p>
			      		<a class="uk-button bh-button-secondary" href="{% url 'stylists' %}">Meet Our Stylists</a>
			    	</div>
			  	</div>

			  	<div class="uk-width-medium-1-3">
			    	<div class="uk-panel uk-panel-box uk-text-center">
			    		<i class="bh-icon-large uk-icon-smile-o"></i>
			      		<h3>No ego. No drama. </h3>
			      		<p>We are only happy when you are happy. Our mission was to take the stress out of getting you to look fabulous for any occasion.</p>
			      		<a class="uk-button bh-button-secondary" href="{% url 'book' %}">Book Now</a>
			    	</div>
			  	</div>

			</div>
		</article>
	</div>
</div>

<div class="bh-position bh-position-light">
    <div class="uk-panel uk-panel-space uk-text-center">
        <h3>What People Think of Blohaute</h3>
        <blockquote>
	      	<p>Blohaute is convenient, cost-effective and beauty-effective. Anyone who wants beautiful hair done easily in the convenience of their own home should definitely contact Blohaute. Amanda, and her team, is amazing.</p>
	      	<small>Jena Hollensteiner</small>
	    </blockquote><br />
	    <blockquote>
	      	<p>Amanda is incredible! She is super friendly and personable! She listens to all of your wants and needs and does magical things with your hair...styles you never thought you could wear! Her in home service and what she does = PRICELESS!!!!</p>
	      	<small>Kelly Legamaro</small>
	    </blockquote>
    </div>
</div>

<div class="bh-position">
	<div class="uk-container uk-container-center">
	    <div class="uk-panel">
	    	<div class="uk-grid" data-uk-grid-margin>

	        	<div class="uk-width-medium-1-5">
	        		<h3 class="uk-margin-top">Recent Styles</h3>
	        	</div>

	        	<div class="uk-width-medium-4-5">

		        	<div class="uk-grid" data-uk-grid-margin data-uk-grid-match>

			            <div class="uk-width-1-2 uk-width-small-1-4 uk-text-center">
			                <img src="http://photos-g.ak.instagram.com/hphotos-ak-xfp1/10785115_330395787165902_1167866336_n.jpg" width="200" height="auto" alt="Client Logo" data-demo-style>
			            </div>

			            <div class="uk-width-1-2 uk-width-small-1-4 uk-text-center">
			                <img src="http://photos-h.ak.instagram.com/hphotos-ak-xaf1/10818054_875819705775495_1766102351_n.jpg" width="200" height="auto" alt="Client Logo">
			            </div>

			            <div class="uk-width-1-2 uk-width-small-1-4 uk-text-center">
			                <img src="http://photos-c.ak.instagram.com/hphotos-ak-xpa1/10424418_295975543927106_2034047788_n.jpg" width="200" height="auto" alt="Client Logo" data-demo-style>
			            </div>

			            <div class="uk-width-1-2 uk-width-small-1-4 uk-text-center">
			                <img src="http://scontent-a-ord.cdninstagram.com/hphotos-xap1/t51.2885-15/926865_1497619350497157_1604890278_n.jpg" width="200" height="auto" alt="Client Logo" data-demo-style>
			            </div>

			        </div>

			    </div>

	        </div>
	    </div>
    </div>
</div>

{% endblock %}

templates/bridal.html
{% extends "base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}
{% block page_title %}Bridal Services{% endblock %}

{% block extra_head %}
{% endblock %}

{% block content %}
    <div class="bh-position bh-position-light bh-position-title">
        <div class="uk-container uk-container-center">
            <div class="uk-panel">
                {% if subtitle %}
                {% else %}
                    <h1>Blohaute Bridal Services</h1>
                {% endif %}
            </div>
        </div>
    </div>

    <div class="uk-container uk-container-center">
        <article class="uk-article uk-grid uk-margin-top uk-margin-bottom">
            <div class="uk-width-medium-1-2">
                <span class="bh-dropcap">N</span>ow introducing Blohaute Bridal!
                We send our highly trained team of stylists right
                to your door for your big day.
                <p>Interested in booking Blohaute for your wedding day hair?
                    Inquire below to check

                    our availability & rates.

                <p><em>Please Note:</em> Bridal Hair Services cannot be booked
                    through our website or app,

                    and must be set up via email. Bridal Pricing differs from
                    regular Blohaute services.

                <div class="uk-panel uk-panel-box">
                    <h2>It's your day to look stunning. We can help make it a
                        guarantee.</h2>

                    <form class="uk-form" method="post" action=".">
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                        <div class="uk-width-medium-1-1 uk-margin-top">
                            <label class="uk-form-label"
                                   for="name">{{ form.name.label }}</label>
                            {% if form.name.errors %}
                                {% render_field form.name placeholder="Enter your name..." class+="uk-form-large uk-width-1-1 uk-form-danger" %}
                                {{ form.name.errors }}
                            {% else %}
                                {% render_field form.name placeholder="Enter your name..." class+="uk-form-large uk-width-1-1" %}
                            {% endif %}
                        </div>
                        <div class="uk-width-medium-1-1 uk-margin-top">
                            <label class="uk-form-label"
                                   for="name">{{ form.email.label }}</label>
                            {% if form.email.errors %}
                                {% render_field form.email placeholder="Enter your email address..." class+="uk-form-large uk-width-1-1 uk-form-danger" %}
                                {{ form.email.errors }}
                            {% else %}
                                {% render_field form.email placeholder="Enter your email address..." class+="uk-form-large uk-width-1-1" %}
                            {% endif %}
                        </div>
                        <div class="uk-width-medium-1-1 uk-margin-top">
                            <label class="uk-form-label"
                                   for="date_of_wedding">{{ form.date_of_wedding.label }}</label>
                            {% if form.date_of_wedding.errors %}
                                {% render_field form.date_of_wedding placeholder="When is the big day?" class+="uk-form-large uk-width-1-1 uk-form-danger uk-hidden" %}
                                {{ form.date_of_wedding.errors }}
                            {% else %}
                                {% render_field form.date_of_wedding placeholder="When is the big day?" class+="uk-form-large uk-width-1-1 uk-hidden" %}
                            {% endif %}

                        </div>
                        <div class="uk-width-medium-1-1 uk-margin-top">
                            <label class="uk-form-label"
                                   for="number_of_bridesmaids">{{ form.number_of_bridesmaids.label }}</label>
                            {% if form.number_of_bridesmaids.errors %}
                                {% render_field form.number_of_bridesmaids placeholder="How many people need hair styling?" class+="uk-form-large uk-width-1-1 uk-form-danger" %}
                                {{ form.number_of_bridesmaids.errors }}
                            {% else %}
                                {% render_field form.number_of_bridesmaids placeholder="How many people need hair styling?" class+="uk-form-large uk-width-1-1" %}
                            {% endif %}

                        </div>
                        <div class="uk-width-medium-1-1 uk-margin-top">
                            <label class="uk-form-label"
                                   for="location">{{ form.location.label }}</label>
                            {% if form.location.errors %}
                                {% render_field form.location placeholder="Where are we doing this?" class+="uk-form-large uk-width-1-1 uk-form-danger" %}
                                {{ form.location.errors }}
                            {% else %}
                                {% render_field form.location placeholder="Where are we doing this?" class+="uk-form-large uk-width-1-1" %}
                            {% endif %}
                        </div>
                        <div class="uk-width-1-1 uk-margin-top">
                            <button class="uk-button bh-button" type="submit">
                                Send
                            </button>
                        </div>

                    </form>
                </div>
            </div>

            <div class="uk-width-medium-1-2">
                <img src="{% static 'images/bridal1_web.jpg' %}"/>
                <img src="{% static 'images/bridal3_web.jpg' %}" class="uk-margin-top"/>
            </div>

        </article>

    </div>
{% endblock %}

{% block extrajs %}
<script src="{% static 'js/pickadate/picker.js' %}"></script>
<script src="{% static 'js/pickadate/picker.date.js' %}"></script>
<script type="text/javascript">
 $(document).ready(function() {
        var datePicker = $('#id_date_of_wedding').pickadate({
            disable: null,
            format: 'ddd mmmm d yyyy',
            formatSubmit: 'yyyy-mm-dd',
            hiddenName: true,
            close: '',
            today: '',
            clear: '',
            min: new Date()
        });
 });
</script>
{% endblock %}

{% block extracss %}
<link rel="stylesheet" href="{% static 'js/pickadate/themes/classic.css' %}">
<link rel="stylesheet" href="{% static 'js/pickadate/themes/classic.date.css' %}">
<link rel="stylesheet" href="{% static 'js/pickadate/themes/classic.time.css' %}">
{% endblock %}

templates/cart.html
{% extends "base.html" %}
{% load staticfiles %}
{% load treatment_slider %} 
{% block page_title %}Cart{% endblock %}
{% block content %}
<div class="bh-position bh-position-light bh-position-title">
    <div class="uk-container uk-container-center">
        <div class="uk-panel">
            <h1>Cart</h1>
        </div>
    </div>
</div>

<div class="bh-position">
    <div class="uk-container uk-container-center">
        <article class="uk-article">
            <div class="uk-grid" data-uk-grid-margin>

                <div class="uk-width-1-1">
                    <div class="uk-overflow-container">
                    <div id="appointment-loading" class="loading-container">
                        <div class="loading-bg"></div>
                        <div class="loading-text">Preparing Cart for Checkout...</div>
                    </div>
                        <table class="uk-table uk-table-middle uk-text-nowrap" id="cart-table">
                            <thead>
                                <tr>
                                    <th>&nbsp;</th>
                                    <th>Service</th>
                                    <th class="uk-text-center">Quantity</th>
                                    <th class="uk-text-center">Subtotal</th>
                                    <th class="uk-text-center">Delete</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% if cart.is_empty %}
                                <tr>
                                <td colspan="6">There are no items in the shopping cart. Add items to your cart to book and schedule your appointment(s).</td>
                                </tr>
                                {% else %}
                                {% for item in cart %}
                                <tr>
                                    <td>
                                        <a href="{% url 'treatment_detail' item.product.slug %}">
                                            <img src="{{item.product.thumb_image_url}}" width="auto" height="75" alt="{{item.product.name}} Cart Item">
                                        </a>
                                    </td>
                                    <td>
                                        <a class="bh-text-uppercase uk-link-reset" href="shop-singleproduct.html">{{ item.product.cart_description }}</a><br>
                                    </td>
                                    <td class="uk-text-center">
                                        <form class="uk-form" action="{% url 'update_quantity' %}" method="POST">
                                            {% csrf_token %}
                                            <input class="uk-form-width-mini" type="number" value={{item.quantity|floatformat:"0"}} min=0 name="quantity">                                               
                                            <input class="" type="hidden" value={{item.pk}} name="pk">                                               
                                            <button class="uk-button">Update</button>
                                        </form>
                                    </td>
                                    <td class="uk-text-center">${{ item.total_price|floatformat:"-2" }} {{ item.product.price_units }}</td>
                                    <td class="uk-text-center"><a href="#" data-pk="{{item.pk}}" class="cart-delete-item"><i class="uk-icon-times"></i></a></td>
                                </tr>
                                {% endfor %}
                                <tr>
                                    <td colspan="6">
                                        <form class="uk-form uk-grid" data-uk-margin>
                                            <div class="uk-width-3-3 uk-text-right">
                                                <a href="{% if user.is_authenticated %}{% url 'schedule' %}{% else %}{% url 'login_register' %}{% endif %}" class="uk-button uk-button-primary" id="checkout-button">Checkout</a>
                                            </div>
                                        </form>
                                    </td>
                                </tr>
                                {% endif %}

                            </tbody>
                        </table>

                    </div>
                </div>
                <br /><br /><br />
                {% treatment_slider %}

                <div class="uk-push-1-2 uk-width-medium-1-2">
                    <div class="uk-panel uk-panel-box uk-panel-header">
                        <h3 class="uk-panel-title">Carts Total</h3>
                        <span class="uk-float-left">Cart Subtotal</span>
                        <span class="uk-float-right">${{cart.cart.total_price|floatformat:"-2"}}</span>
                        <br><br>
                        <span class="uk-float-left">Order Total Price</span>
                        <span class="uk-float-right">${{cart.cart.total_price|floatformat:"-2"}}</span>
                        <br />
                        <hr />
                        <span class="uk-float-left"><i class="uk-icon-money uk-text-large"></i> ALL TIPS SHOULD BE MADE IN CASH <i class="uk-icon-money uk-text-large"></i><br />Also stylists do not carry cash on so we can not break large bills</span>

                    </div>
                </div>

            </div>
        </article>

    </div>
</div>
{% endblock %}

{% block extrajs %}
<script>
$( document ).ready(function() {
    $('.cart-delete-item').click(function(e) {
        e.preventDefault();

        data = {'pk': $(this).data('pk')}
        var form = document.createElement('form');
        form.setAttribute('action', '{% url 'remove_cart_item' %}');
        form.setAttribute('method', 'POST');
        var input1 = document.createElement('input');
        input1.value = $(this).data('pk');
        input1.name = 'pk'
        var input2 = document.createElement('input');
        input2.value =  getCookie('csrftoken');
        input2.name = 'csrfmiddlewaretoken';
        form.appendChild(input1);
        form.appendChild(input2);
        $(form).appendTo('body').submit()
    });
});
</script>
<script>
$('#appointment-loading').hide();

$("#checkout-button").click(function(){
    $('#appointment-loading').show();
    $('#cart-table').css({position: 'relative'});
    var spinner = new Spinner().spin();
    $(spinner.el).appendTo(document.getElementById('appointment-loading'));
});
</script>
{% endblock %}

templates/package_checkout.html
{% extends "minimal_base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block page_title %}Checkout{% endblock %}

{% block content %}

<div class="bh-position">
    <div class="uk-container uk-container-center">

        <ul class="uk-breadcrumb">
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'book' %}">Book</a></li>
            <li class="uk-active"><span>Checkout</span></li>
        </ul>

        <article class="uk-article">
            <div class="uk-grid" data-uk-grid-margin>
                {% if checkout_form.errors %}
                <div class="uk-width-1-1">
                    <div class="uk-alert uk-alert-danger ">
                        {% if checkout_form.non_field_errors %}
                            {% for error in checkout_form.non_field_errors %}
                                <p>{{error}}</p>
                            {% endfor %}
                        {% else %}
                            There was a problem booking your order. Please correct the errors below and try again.
                        {% endif %}

                    </div>
                </div>
                {% endif %}
                <div class="uk-width-1-1">
                    <h1>You will be able to schedule your appointements after checking out</h1>
                    {% with WIDGET_ERROR_CLASS='uk-form-danger' WIDGET_REQUIRED_CLASS='required' %}
                        {% for hidden in checkout_form.hidden_fields %}
                            {{ hidden }}
                        {% endfor %}
               
                        <div class="uk-grid uk-margin-large-top" data-uk-grid-margin>
                            {# if paying with series, order summary left, empty div right#}
                    
                            <form id="checkout-form" method="POST" class="uk-form uk-width-medium-1-2">
                                {% csrf_token %}
                                {% include 'form_snippets/appointment_payment.html' %}
                            </form>   
    
                            <div class="uk-width-medium-1-2" id="order-summary-container">
                                {% include 'form_snippets/single_item_order_summary.html' %}
                            </div>
                        </div>
                    {% endwith %}
                </div>
            </div>
        </article>

    </div>
</div>
{% endblock %}

{% block extrajs %}
<script>
$(document).ready(function() {
    $("#place-order-button").click(function() {
        $("#checkout-form").submit();
    });
});

</script>
{% endblock %}